# Generated by Django 5.1.4 on 2024-12-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
    # Remove or comment out this line
    # migrations.AddField(
    #     model_name='task',
    #     name='priority',
    #     field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
    # ),
]

